//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJFile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public string Md5 { get; set; }
        public string Qycode { get; set; }
        public string Month { get; set; }
        public string Directory { get; set; }
        public string FileName { get; set; }
        public string FullPath { get; set; }
        public string Extension { get; set; }
        public string ContentType { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string ID { get; set; }
        public string fileinfo { get; set; }
        public string filesize { get; set; }
        public string ylinfo { get; set; }
        public string isyl { get; set; }
    }
}
