//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJFile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qycode
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IsUsed { get; set; }
        public long ID { get; set; }
        public string secret { get; set; }
        public string space { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<System.DateTime> crdate { get; set; }
        public Nullable<long> filecount { get; set; }
        public string yyspace { get; set; }
    }
}
