//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJFile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string username { get; set; }
        public string pasd { get; set; }
        public long ID { get; set; }

        public string UserRealName { get; set; }

        public string Role { get; set; }

        public long Space { get; set; }

    }
}
